### ISSUE TITLE
Remove duplicate database table information & organize wireframes.

### ISSUE THREAD

**Issue by alejo4373** [AminesCodes/Fashion-Sustainability#8]
@lakerfan1994 @sislam16 @AminesCodes @tbriany 
Really liked your README. Very concise and clear. For the Database Structure just leave the image and remove the description below it that basically contains the same info. Also for the wireframes just create a `wireframes.md` file then link your images there to display. In `README.md` you just have a link pointing to `wireframes.md`

**Comment by AminesCodes** [comment]
Thank you for your feedback and suggestions
